version: 2
jobs:
  test:
    docker:
      - image: ngocnd0607/circleci-build
    working_directory: /go/src/github.com/circleci/circleci-demo
    steps:
      - checkout
      - echo "test done"
  deploy-prod:
    docker:
      - image: ngocnd0607/circleci-build
    working_directory: /go/src/github.com/circleci/circleci-demo
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install depent
          command: |
            glide up 
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build and push Docker image
          command: |
            TAG="0.1.${CIRCLE_BUILD_NUM}"
            docker build -t ngocnd0607/circleci-demo .
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push ngocnd0607/circleci-demo
      - run:
          name: Deploy to eb
          command: |
            bash ./setup.sh
            cd eb-deploy
            eb deploy ci-production-env
  deploy-stage:
    docker:
      - image: ngocnd0607/circleci-build
    working_directory: /go/src/github.com/circleci/circleci-demo
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install depent
          command: |
            glide up 
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build and push Docker image
          command: |
            TAG="0.1.${CIRCLE_BUILD_NUM}"
            docker build -t ngocnd0607/circleci-demo .
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push ngocnd0607/circleci-demo
      - run:
          name: Deploy to eb
          command: |
            bash ./setup.sh
            cd eb-deploy
            eb deploy ci-stage-env
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy-stage:
          filters:
            branches:
              only: develop
      - deploy-prod:
          filters:
            branches:
              only: master  